### ISSUE TITLE
从服务器获取的题目中含有\n换行符，导致终端输出 random answer

### ISSUE THREAD

**Issue by TscCai** [QuincyC379/liangongbao#2]
从服务器获取的一些题目中含有\n换行符，导致在本地题库搜索时找不到题目，随机选答案。例如题库中的第515行，其他类似的多人对话选人的题目可能都存在此问题

**Comment by QuincyC379** [comment]
不用改，也不需要了解原理，得满分就是王道啊

**Comment by TscCai** [comment]
不影响得满分？那没事了！
